### ISSUE TITLE
Text will just fall off the edge of the gif

### ISSUE THREAD

**Issue by ienadlard** [sanidhya711/text-on-gif#10]
some basic text wrapping would be nice

**Comment by ienadlard** [comment]
I also do not mind looking into this one, i feel like it shouldnt be too difficult :^)

**Comment by sanidhya711** [comment]
![image](https://user-images.githubusercontent.com/59452778/155477158-5652441f-51fb-4ffe-ac78-2ac43b667916.png)
well I planned on fixing that from the very start. *planned* 😂
If you feel like fixing it, please do 🥺🥺

**Comment by sanidhya711** [comment]
Working on it. [Duplicate](https://github.com/sanidhya711/text-on-gif/issues/7)

**Comment by ienadlard** [comment]
Was this closed as a dupe bc it is being worked on with that other issue? or do you still need someone to look at this?

**Comment by sanidhya711** [comment]
Hi, I closed it as it was a duplicate and im working on fixing it. Expect the fix to be out by tomorrow. 😄

**Comment by sanidhya711** [comment]
Just published a new verison. Supports basic text wrapping now, will update the readme in the next update and also thinking of adding multi line support by inserting \n or something
