### ISSUE TITLE
Specific Frames 

### ISSUE THREAD

**Issue by robke96** [sanidhya711/text-on-gif#17]
Hello, is there any way to add text on specific frames like on first 20 frames text would be and then disappear?

**Comment by sanidhya711** [comment]
Hi. We dont have this feature right now but this sounds pretty useful and also easy to implement. Plan on adding it soon.

**Comment by sanidhya711** [comment]
Hey, checkout the new version. 

You can finally implement what youre looking for by listening to the "on frame" event and setting the gif.font_color to transparent on the frames you dont want text on. 

For example:
```
gif.on("on frame",(frameIndex)=>{ 
  if(frameIndex <= 20){ 
    gif.font_color = "white"; 
  }else{ 
    gif.font_color = "transparent";
  }
 }); 
```
