### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by hardianto01** [sanidhya711/text-on-gif#2]
![Screenshot_2021-06-02-11-26-22-298_com microsoft rdc android](https://user-images.githubusercontent.com/71861395/120419614-5e9fb380-c395-11eb-9865-125f43f34929.jpg)
how ??

**Comment by sanidhya711** [comment]
is the gif that you're trying to write on too long? does it have a very high frame rate? im aware of this issue but havent fixed it yet because I had forgotten bout this package. i'll try to fix it with 1-2 days. also you should sleep early XD

**Comment by hardianto01** [comment]
> is the gif that you're trying to write on too long? does it have a very high frame rate? im aware of this issue but havent fixed it yet because I had forgotten bout this package. i'll try to fix it with 1-2 days.

I use gif from readme.md then I post it to imgbb and I implement it in my code

**Comment by sanidhya711** [comment]
are you using a old version of node? try updating it or try increasing the memory allocated to node. meanwhile i'll try to fix the memory leaks in my code(if i find any)

**Comment by hardianto01** [comment]
![Screenshot_2021-06-02-14-18-49-042_com microsoft rdc android](https://user-images.githubusercontent.com/71861395/120433258-961a5a00-c3ad-11eb-8eaf-63843ea1abf8.jpg)
Saya menggunakan v.14.17

**Comment by hardianto01** [comment]
![Screenshot_2021-06-02-14-22-27-280_com microsoft rdc android](https://user-images.githubusercontent.com/71861395/120433616-09bc6700-c3ae-11eb-9e6f-24a13a4335ac.jpg)
i try again use devploy to heroku and similarity

**Comment by sanidhya711** [comment]
try running it locally again. but before that use this in ur command line **export NODE_OPTIONS="--max-old-space-size=8192"**
also could you give me the link to ur gif?

**Comment by hardianto01** [comment]
https://hardianto-chan.herokuapp.com/api/creator/memeGif?urlGif=YOUR_URL&text=customMessage&apikey=hardianto

**Comment by sanidhya711** [comment]
this url gives me a error. it says application error. try uploading the gifs to imgur maybe or give me the imgbb link

**Comment by hardianto01** [comment]
> this url gives me a error. it says application error. try uploading the gifs to imgur maybe or give me the imgbb link
https://i.ibb.co/2hnhDSw/68747470733a2f2f692e696d6775722e636f6d2f484f6435586b312e676966.gif

**Comment by sanidhya711** [comment]
umm im making some changes so wait 5-10 mins

**Comment by sanidhya711** [comment]
> > this url gives me a error. it says application error. try uploading the gifs to imgur maybe or give me the imgbb link
> > https://i.ibb.co/2hnhDSw/68747470733a2f2f692e696d6775722e636f6d2f484f6435586b312e676966.gif

this url did work and it was able to write it as a file. also i published a new version where i replaced the foreach loop with a while loop to make it faster 
![speed](https://user-images.githubusercontent.com/59452778/120437596-e5588e80-c39d-11eb-86c2-9b6875fc9683.PNG)

**Comment by hardianto01** [comment]
![Screenshot_2021-06-02-15-30-40-528_com microsoft rdc android](https://user-images.githubusercontent.com/71861395/120441840-90c20d00-c3b7-11eb-988f-ba7b4193a4f7.jpg)
this work and how to set option in heroku

**Comment by sanidhya711** [comment]
what worked? export NODE_OPTIONS="--max-old-space-size=8192 this? or updating the package? also i dont think heroku supports increasing the space size

**Comment by sanidhya711** [comment]
update to the latest version of the package and the error should be fixed now . you don't need to use this anymore: export NODE_OPTIONS="--max-old-space-size=8192

**Comment by hardianto01** [comment]
don't work this heroku

**Comment by sanidhya711** [comment]
huh? what do you mean???

**Comment by sanidhya711** [comment]
> don't work this heroku

it works now. right?

**Comment by sanidhya711** [comment]
@all-contributors please add @Cryptizism for Documentation
