### ISSUE TITLE
Image too large

### ISSUE THREAD

**Issue by ifdiego** [sanidhya711/text-on-gif#22]
Hey, I'm getting a gif a little bit large, almost 2mb. Is there a way to generate the gif smaller? Or compress while encoding?

**Comment by sanidhya711** [comment]
Yes, compressing it is possible but for this feature to be inbuilt I will have to make a few changes to the library. You can implement it on your own too by making a few other encoding constants like **setQuality, setThreshold, algorithm, and useOptimizer** to variable so users can set them on the go to get the desiered file size/quality.  For reference here is the [documentation ](https://www.npmjs.com/package/gif-encoder-2#constructor)of the gif encoder that is being used in **TextOnGif**

**Comment by ifdiego** [comment]
Oh hey,

I did play a little bit with setQuality, setThreshold and algorithm using the documentarion you sent.
It did end up with a slightly smaller gif. 
I think I managed what I was aiming.

Thanks!
