### ISSUE TITLE
Generated broken GIF.

### ISSUE THREAD

**Issue by ianwijma** [sanidhya711/text-on-gif#4]
Loving the project idea, but just can't get it to work. I keep getting a buggy image (looks like the too many frames issue). But I only have like 47 frames (I think).

Here is the code I currently have, its bare minimum but still seems to have issues:

```js
  const filePath = path.join("public", "input.gif");
  const outPath = path.join("public", "out.gif");

  await textOnGif({
    file_path: filePath,
    write_as_file: true,
    getAsBuffer: false,
    write_path: outPath,
  });
```

input.gif
![input.gif](https://user-images.githubusercontent.com/17692119/133190489-905c9206-40cd-4233-981e-215e44fc0a75.gif)

output.gif
![output.gif](https://user-images.githubusercontent.com/17692119/133190501-f84e416f-ac24-445d-a1a4-ca397344493b.gif)

**Comment by sanidhya711** [comment]
@ianwijma im aware of this issue but too lazy to fix it...will do it now that you've mentioned it. Give me two days.
It will probably be fixed by the day after tomorrow.
Again sorry for the inconvenience. Its a shitty library D:

**Comment by ianwijma** [comment]
Hey @sanidhya711 

Its free and you should not feel pressured to fix it! If there are some limitations to the GIFs size, frame count, FPS. Just let me know, I can work around it. Than maybe we can note them in the `readme` so other people know about them :) Saves you dev time :D

**Comment by ianwijma** [comment]
I was thinking about maybe working on a PR that adds addition functionality like fade in/out of text and drawing. But that might be out of scope of this package :D

**Comment by sanidhya711** [comment]
I plan on working on this package extensively and adding much more functionality but im a little busy these days. I have exams coming up and am also working on a few other projects. After all that stuff is over i'll make this library much bigger and useful.
When that time comes and the library actually starts to work I expect people to make PR's. Thanks.

**Comment by sanidhya711** [comment]
Also the bug dosen't depend of the gif size now. Its having issues fixing the color indexes and stuff.
I plan on changing almost all the inner functionality of the library and use a better way to write on gif. 
When thats done, all post requests and contributors will be welcome.
It will become way faster too... :)

**Comment by legendhimself** [comment]
> Also the bug dosen't depend of the gif size now. Its having issues fixing the color indexes and stuff. I plan on changing almost all the inner functionality of the library and use a better way to write on gif. When thats done, all post requests and contributors will be welcome. It will become way faster too... :)

Hey, Great job! I've been experiencing the same issue. Tried fixing it but failed. How much time would it take you to launch an update?, This lib is unique and I really love this lib.

**Comment by sanidhya711** [comment]
Got some major exams from 15 nov ;-;
Maybe before that and if not, then definitely after december 2nd and before december 10th

**Comment by sanidhya711** [comment]
Also i'll put some massage regarding the same in the readme so others know about it before they begin to use the library. Thanks

**Comment by legendhimself** [comment]
> Got some major exams from 15 nov ;-; Maybe before that and if not, then definitely after december 2nd and before december 10th

Good Luck, Ive done some research and found out a library which works with transparent pixels and others pixels which gifwrap doesnt work with.

Ill try to fix it by today or tomorrow and I'll make a pr if I am successful in it.

**Comment by sanidhya711** [comment]
Thanks and good luck to you too 👍

**Comment by WrenchDev** [comment]
Uhm me and my other developer friends are still waiting for this bug to be fixed lol

**Comment by sanidhya711** [comment]
> Uhm me and my other developer friends are still waiting for this bug to be fixed lol
😅😂😂 i have exams that are ending on 15rh December.  I swear i'll fix it after that and release new features. It would really help if you could fix it before than and contribute to this. Im releasing the new version in december anyways

**Comment by WrenchDev** [comment]
> > Uhm me and my other developer friends are still waiting for this bug to be fixed lol
> > 😅😂😂 i have exams that are ending on 15rh December.  I swear i'll fix it after that and release new features. It would really help if you could fix it before than and contribute to this. Im releasing the new version in december anyways

Me and my other friends are trying to catch this issue and find a solve for that by the way good luck on your exams!

**Comment by WrenchDev** [comment]
This bug seems to be: https://github.com/jtlapp/gifwrap/issues/10

**Comment by sanidhya711** [comment]
oh really thanks for doing the work for me. Looks like they failed at fixing that issue and that library is no longer maintained. Somewhere in the comments a person mentioned that they switched to https://github.com/matt-way/gifuct-js and said that it works perfectly. Now that we know what to use it will be much faster to change the library. If you have the time and are willing to fix it then its much appreciated. Thanks

**Comment by WrenchDev** [comment]
I'll try my best

**Comment by sanidhya711** [comment]
Alright found something that works. Will push it soon 😂😂(SOON)

**Comment by WrenchDev** [comment]
> 

Great!

**Comment by sanidhya711** [comment]
![gif-with-text](https://user-images.githubusercontent.com/59452778/147109290-038bf263-7bd2-4927-bc32-04d8ed17e896.gif)

**Comment by sanidhya711** [comment]
FIXED :D

**Comment by ianwijma** [comment]
Awesome, thanks!

**Comment by sanidhya711** [comment]
@all-contributors please add @ianwijma for Bug reports

**Comment by sanidhya711** [comment]
https://github.com/all-contributors please add @hydradev00 for Bug reports

**Comment by sanidhya711** [comment]
@all-contributors please add @hydradev00  for Bug reports
