### ISSUE TITLE
Support for text outline

### ISSUE THREAD

**Issue by ienadlard** [sanidhya711/text-on-gif#8]
For instance it would be nice to specify white text with black outline

**Comment by sanidhya711** [comment]
Oh nice idea 👍 will definitely add that soon. Im a little busy with some other projects too at the moment so if possible try taking a look at the source code and see if you could add that and make a pr. It is now using a canvas internally so it should be pretty simple to add outline thingy. Anyways i'll try to add it soon

**Comment by ienadlard** [comment]
I just looked up the documentation for canvas and it should be pretty straightforward. I see what I can do.

**Comment by ienadlard** [comment]
see PR #9

**Comment by sanidhya711** [comment]
Merged it. Thanks for contributing 🙌🙌

**Comment by sanidhya711** [comment]
@all-contributors please add @ienadlard  for Code

**Comment by sanidhya711** [comment]
https://github.com/all-contributors please add @Cryptizism for Documentation
